# Discord Bot Token (https://discord.com/developers/applications)
# Оставь пустым, если не используешь Discord-синхронизацию
bot-token: ""

# ID канала для синхронизации чата
chat-channel-id: ""

# ID бота (чтобы игнорировать свои же сообщения)
bot-user-id: ""

# Форматы сообщений
format:
  global: "<bold><gold>G</bold> <gray>%s: <white>%s"
  local: "<bold><green>L</bold> <gray>%s: <white>%s"
  minecraft-to-discord: "**%s**: %s"
  discord-to-minecraft: "<{prefix}>[Discord] <{name}>%s: <{message}>%s"

# Цвета для Discord -> Minecraft чата
# Доступные цвета: black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple,
# gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
colors:
  discord-prefix: "gray"
  discord-name: "aqua"
  discord-message: "white"
